# Generated by Django 5.2.5 on 2025-08-17 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Passkey name')),
                ('platform', models.CharField(default='', max_length=255, verbose_name='Platform')),
                ('credential_id', models.CharField(max_length=255, verbose_name='Credential ID')),
                ('token', models.CharField(help_text='Attested credential data which is encoded by websafe-base64 string', max_length=255, verbose_name='Token')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Passkey status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_used', models.DateTimeField(default=None, null=True, verbose_name='Last used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'passkey',
                'verbose_name_plural': 'passkeys',
                'constraints': [models.UniqueConstraint(fields=('user', 'credential_id'), name='passkey_unique_user_credential')],
            },
        ),
    ]
