# Generated by Django 5.2.5 on 2025-08-17 04:19

from django.db import migrations

def create_default_users(apps, schema_monitor):
    UserModel = apps.get_model('sample_app', 'CustomUser')
    UserModel.objects.create_superuser(email='superuser@sample.local', password='superUser001@password', nick_name='admin')
    UserModel.objects.create_user(email='test-user@sample.local', password='testUser002@password', nick_name='test user')

class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_users)
    ]
